### ISSUE TITLE
Show `No Connections` alert on instant action if no suitable connections

### ISSUE THREAD

**Issue by ConstantinKV** [saltedge/sca-authenticator-ios#161]
User has not linked authenticator.
User scans instants action's QR and see PROCESSING screen.

**Comment by AlexLobaciov** [comment]
@baller784 does not work when there are other connections (different from the one I am signing in). Expected result - if there are no connections - error with "no connections available", and if there are connections but there is no suitable connection - also error with "no ocnnections available". Thanks!
