### ISSUE TITLE
The certificate for this server is invalid

### ISSUE THREAD

**Issue by deamul1sk** [saltedge/sca-authenticator-ios#67]
**Summary:**  
`Summary of the problem goes here`

**Steps to reproduce:**  
1.  
2.  
3.  

**Actual behavior:**  
`Tell us what happens instead`

**Expected behavior:**  
`Tell us what should happen`

**Screenshots (if applicable)**  

**Details**  
`Configuration, environment, gem/ruby version, OS, etc.`

**Comment by ConstantinKV** [comment]
Please verify your server SSL configuration.

**Comment by baller784** [comment]
@deamul1sk I think, that you are using http server, or https with self-signed ssl certificate, which is not permitted by Authenticator app.

**Comment by deamul1sk** [comment]
I am sorry, this is a post issue due to my mistake, really sorry
