### ISSUE TITLE
The certificate for this server is invalid

### ISSUE THREAD

**Issue by deamul1sk** [saltedge/sca-authenticator-ios#68]
**Summary:**  
`I'm having a certificate related error.`

**Steps to reproduce:**  
1.  Run SCA Identity Service with SSL config
2.  Run Authenticator App
3.  Connect Provider 
![image](https://user-images.githubusercontent.com/36152586/72342606-6bb7f600-36ff-11ea-8d6d-d6b452739827.png)
4. I have a certificate error in Authenticator
![image](https://user-images.githubusercontent.com/36152586/72342721-bfc2da80-36ff-11ea-9fa7-567cb871e5cb.png)
![image](https://user-images.githubusercontent.com/36152586/72342786-e7b23e00-36ff-11ea-9217-778bfe98369a.png)

**Actual behavior:**  
`I know my certificate is not trusted.  So do you have a solution temporarily disable certificate authentication to go?  And can you show me the code to process the certificate check in the Authenticator project source.  I really want to know'

Looking forward to your early reply.
Thanks,
Deam

**Comment by baller784** [comment]
@deamul1sk 

Try this: https://cocoacasts.com/how-to-add-app-transport-security-exception-domains

**Comment by deamul1sk** [comment]
> @deamul1sk
> 
> Try this: https://cocoacasts.com/how-to-add-app-transport-security-exception-domains

@baller784 

What do i do with this, please, I'm not a Swift programmer

**Comment by deamul1sk** [comment]
@baller784 

I don't know if i got it right. I have followed the instructions that you have shown. I have configured this code to info.plist file (<sca-authenticator-ios-master>/Example/Authenticator/Supporting Files/info.plist):
![image](https://user-images.githubusercontent.com/36152586/72402323-8337c300-3781-11ea-8c8b-4f97d2b0b7b4.png)

And the result is still the same

**Comment by baller784** [comment]
@deamul1sk 

If I understood it right, you created a new `info.plist`. If so, that's not right. There is an `Info.plist` already. Here it is:

https://github.com/saltedge/sca-authenticator-ios/blob/master/Example/Authenticator/Supporting%20Files/Info.plist

In Xcode, just right click on the `Info.plist` -> Open As -> Source Code. Find the line with `NSAppTransportSecurity` key (Line 36). Try to add there:

```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSExceptionDomains</key>
    <dict>
        <key>192.168.11.196</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSIncludesSubdomains</key>
            <true/>
        </dict>
    </dict>
</dict>
```

**Comment by deamul1sk** [comment]
@baller784 

I got this error when i named Info.plist:
<img width="1440" alt="Screen Shot 2020-01-16 at 10 18 02" src="https://user-images.githubusercontent.com/36152586/72490473-e42ace00-3849-11ea-96cb-3e3f4b461fb4.png">
so, i changed it to info.plist. I wonder if i did it right?

If i'm right, i have configured according to your lines .... And the result is still the same

Thanks for your enthusiasm, I don't know how to do it anymore

**Comment by baller784** [comment]
@deamul1sk 

Try to remove reference to `info.plist` from Xcode and add it again to the project.

- Right click on `info.plist` -> Delete -> Remove Reference
- Then right click on the Supporting Files folder -> Add Files to "Authenticator" -> Tap on `Info.plist` -> Add

1.
![Screen Shot 2020-01-16 at 11 46 37](https://user-images.githubusercontent.com/17417787/72513614-dbd89000-3855-11ea-9a0c-992bc0990143.png)

2.
![Screen Shot 2020-01-16 at 11 47 02](https://user-images.githubusercontent.com/17417787/72513648-eb57d900-3855-11ea-8004-bcac219d7402.png)

3.
![Screen Shot 2020-01-16 at 11 48 23](https://user-images.githubusercontent.com/17417787/72513737-1b06e100-3856-11ea-8705-9e2a85939189.png)

4.
![Screen Shot 2020-01-16 at 11 48 42](https://user-images.githubusercontent.com/17417787/72513764-278b3980-3856-11ea-8125-6af0cfc6a42c.png)

**Comment by deamul1sk** [comment]
@baller784 

I tried downloading the new source code on git and rebuild.

Steps to reproduce:
1. cd sca-authenticator-ios/Example
2. bundle install
3. pod install
4. Create application.plist configuration file using application.example.plist (on /Supporting Files)
5. Open project's workspace file in Xcode (Example/Authenticator.xcworkspace)
6. Build
Then, I got this error
"error: could not read data from '/SCA_IDENTITY_SERVICE/sca-authenticator-ios-master 3/Example/Authenticator/Supporting Files/info.plist': The file “info.plist” couldn’t be opened because there is no such file"

I'm sorry but can you help me rebuild  on your computer?

**Comment by baller784** [comment]
@deamul1sk 

There is no problem with the source code or the project configuration. The problem is, that you somehow missed the `Info.plist` file. Please tap on the `Supporting Files` and open it in Finder.

You should see it both in the Xcode and inside the root of the project.

![Screen Shot 2020-01-17 at 13 41 23](https://user-images.githubusercontent.com/17417787/72610032-0ea28700-392f-11ea-8472-6b8ba9b1bcbe.png)

<img width="443" alt="Screen Shot 2020-01-17 at 13 39 02" src="https://user-images.githubusercontent.com/17417787/72609892-ba97a280-392e-11ea-8757-3a62fa97cd77.png">

Then, only when you have it both in the project and in the root, try next:

<img width="1680" alt="Screen Shot 2020-01-17 at 13 59 15" src="https://user-images.githubusercontent.com/17417787/72611254-49f28500-3932-11ea-8639-2bec4d46eee0.png">

1. Navigate to the project (select it in the Project navigator)
2. Select the application target in the list of targets
3. Click the Build Settings tab.
4. Type `info.plist` inside the search bar
5. Under the Packaging section, make sure the `Info.plist` is properly set to the location/file name. It should be exactly the same as on the screenshot. 

`Authenticator/Supporting Files/info.plist`

**Comment by deamul1sk** [comment]
@baller784 

really thank you when i got to Info.plist but the result is still error.
<img width="1440" alt="Screen Shot 2020-01-18 at 14 41 43" src="https://user-images.githubusercontent.com/36152586/72660451-e5522b80-3a00-11ea-84d2-86f1c5eadae2.png">
<img width="908" alt="Screen Shot 2020-01-18 at 14 48 02" src="https://user-images.githubusercontent.com/36152586/72660502-95279900-3a01-11ea-8ab5-6966bd0c9185.png">


I know you tried a lot already but what shout i do next :((

**Comment by deamul1sk** [comment]
@baller784 

Thank you very much, I'm fixing this issue through a trusted cert.

<img width="375" alt="Screen Shot 2020-01-20 at 16 37 02" src="https://user-images.githubusercontent.com/36152586/72715500-28e49b00-3ba3-11ea-9551-13fd69fc6b29.png">
