### ISSUE TITLE
Batch endpoints to reduce API calls?

### ISSUE THREAD

**Issue by alexrmacleod** [saltedge/sca-authenticator-ios#88]
Any idea where the "batch endpoint", to make it possible to retrieve things like their transaction histories and balances for all accounts and cards relating to a customer within in a single API request is? 

Can't seem to find it in the docs. Looking to reduce the number of API calls.

**Comment by AlexLobaciov** [comment]
Good day. Thanks for your question. The current repository is related to the solution for Strong Customer Authentication and is not somehow related to the retrieving accounts and transactions. You can visit www.saltedge.com for our Data Aggregation platform. 
Also, maybe you're looking for iOS SDK for the Data Aggregation platform - then you need this repository: https://github.com/saltedge/saltedge-ios-swift.

In any case, in case of any questions, please leave a message to Salt Edge support team (https://www.saltedge.com/pages/contact_support), as this repository is meant for product development.

Closing issue.
